@extends('layouts.principal')
@section('titulo','produtos.blade.php')    
@section('conteudo')    
    <h3>Produtos</h3>
    <ul>
        <li>Notebook</li>
        <li>Impressora</li>
        <li>Monitor</li>
        <li>Mouse</li>
        <li>Teclado</li>
        <li>Câmera</li>        
    </ul>    
@endsection('conteudo')